/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-jul.-2017 7:28:49 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS spEstadoEquipo CASCADE
;

/* Create Tables */

CREATE TABLE spEstadoEquipo
(
	fkEquipo integer NOT NULL,
	motivo varchar(50),
	estado varchar(25),
	fecha timestamp,
	fkPersonal integer
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE spEstadoEquipo ADD CONSTRAINT PK_spEstadoEquipo
	PRIMARY KEY (fkEquipo)
;
