/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 05-dic.-2016 6:08:10 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS spimproductiva_pkimproductiva_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS spImproductiva CASCADE
;

/* Create Tables */

CREATE TABLE spImproductiva
(
	pkImproductiva integer NOT NULL   DEFAULT NEXTVAL(('"spimproductiva_pkimproductiva_seq"'::text)::regclass),
	codigo varchar(4),
	descripcion varchar(50)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE spImproductiva ADD CONSTRAINT PK_spImproductiva
	PRIMARY KEY (pkImproductiva)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE spimproductiva_pkimproductiva_seq INCREMENT 1 START 1
;
